

import type { UserProfile, GameState, CompetitorLogEntry, PeerData, RoleActionItems, Task } from "@/types";

export const USER_PROFILES: UserProfile[] = [
  { id: 'procurement', name: 'Procurement', avatarUrl: 'https://picsum.photos/seed/procurement/100/100' },
  { id: 'production', name: 'Production', avatarUrl: 'https://picsum.photos/seed/production/100/100' },
  { id: 'logistics', name: 'Logistics', avatarUrl: 'https://picsum.photos/seed/logistics/100/100' },
  { id: 'sales', name: 'Sales', avatarUrl: 'https://picsum.photos/seed/sales/100/100' },
];

export const INITIAL_GAME_STATE: GameState = {
  companyValuation: 50000000,
  netIncome: 2500000,
  inventoryValue: 750000,
  totalEmissions: 1200,
  teamStrategy: "Focus on high-margin products and expand market share in Europe.",
  kpiHistory: [
    { round: 1, companyValuation: 45000000, netIncome: 1800000, inventoryValue: 600000, totalEmissions: 1100 },
  ],
  timerState: {
    timeLeft: 1200,
    isPaused: true,
    isBreakActive: false,
    isBreakEnabled: true,
    roundDuration: 1200, // 20 minutes
    breakDuration: 300, // 5 minutes
  }
};


export const ALL_TASKS: Task[] = [
  // --- ROUND 1 SETUP TASKS ---
  {
    id: "T0.1",
    title: "Confirm Initial Finished Goods Stock",
    description: "Verify and adjust the starting inventory levels for all finished products. This is a one-time setup for Round 1. Use transaction ZMB52 to check current stock.",
    role: "Logistics",
    transactionCode: "ZMB1B (for changes)",
    priority: "Critical",
    estimatedTime: 5,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Nut_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Blueberry_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Strawberry_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Raisin_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Original_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Mixed_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Nut_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Blueberry_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Strawberry_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Raisin_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Original_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Mixed_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
    ]
  },
  {
    id: "T0.2",
    title: "Confirm Initial Raw Material Stock",
    description: "Verify and adjust the starting inventory for all raw materials. This is a one-time setup for Round 1. Use transaction ZMB52 to check current stock.",
    role: "Procurement",
    transactionCode: "ZME21N (for changes)",
    priority: "Critical",
    estimatedTime: 5,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Wheat_Initial_Stock_kg", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Oats_Initial_Stock_kg", dataType: "Integer", suggestedValue: 30000 },
      { fieldName: "Nuts_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Blueberries_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Strawberries_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Raisins_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Small_Bag_Initial_Stock_units", dataType: "Integer", suggestedValue: 150000 },
      { fieldName: "Large_Bag_Initial_Stock_units", dataType: "Integer", suggestedValue: 100000 },
      { fieldName: "Small_Box_Initial_Stock_units", dataType: "Integer", suggestedValue: 150000 },
      { fieldName: "Large_Box_Initial_Stock_units", dataType: "Integer", suggestedValue: 100000 },
    ]
  },
  {
    id: "T0.3",
    title: "Validate & Confirm Bill of Materials (BOM)",
    description: "Check the recipes (BOM) for all products to ensure they are correct before starting production. Use ZCS02 to make changes if needed. This is a one-time setup for Round 1.",
    role: "Production",
    transactionCode: "CS03 (View), ZCS02 (Change)",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T0.4",
    title: "Set Initial Prices",
    description: "Set the initial selling price for all products in all distribution channels (DC). This is a critical one-time setup for Round 1.",
    role: "Sales",
    transactionCode: "VK32",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Nut_Muesli_500g_Price", dataType: "Currency", suggestedValue: 3.90 },
      { fieldName: "Blueberry_Muesli_500g_Price", dataType: "Currency", suggestedValue: 4.23 },
      { fieldName: "Nut_Muesli_1kg_Price", dataType: "Currency", suggestedValue: 4.61 },
      { fieldName: "Blueberry_Muesli_1kg_Price", dataType: "Currency", suggestedValue: 5.26 },
    ]
  },
  // --- REGULAR TASKS ---
  {
    id: "T1",
    title: "Forecast Sales",
    description: "Create the sales forecast for all products for the upcoming period.",
    role: "Sales",
    transactionCode: "MD61",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Total_Units_Forecasted", dataType: "Integer", suggestedValue: 370000 },
    ]
  },
  {
    id: "T2",
    title: "Plan Production",
    description: "Run MRP and convert planned orders to production orders.",
    role: "Production",
    transactionCode: "MD01, CO41",
    priority: "Critical",
    estimatedTime: 15,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T3",
    title: "Procure Raw Materials",
    description: "Order raw materials needed for the production plan.",
    role: "Procurement",
    transactionCode: "ZME21N",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T4",
    title: "Check Inventory Report",
    description: "Continuously monitor inventory levels of raw materials and finished goods.",
    role: "Logistics",
    transactionCode: "ZMB52",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T5",
    title: "Review Market Reports",
    description: "Analyze market reports to understand competitor pricing and market share.",
    role: "Sales",
    transactionCode: "ZMARKET",
    priority: "High",
    estimatedTime: 10,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "ERPsim Gather Data",
    taskType: "ERPsim Gather Data",
    completed: false,
    dataFields: [{ fieldName: "Competitor_Avg_Price", dataType: "Currency" }]
  },
  {
    id: "T6",
    title: "Set Product Prices",
    description: "Adjust the selling price for all finished products based on strategy and market data.",
    role: "Sales",
    transactionCode: "VK32",
    priority: "High",
    estimatedTime: 8,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T5"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      {
        fieldName: "Blueberry_Muesli_1kg_Price",
        dataType: "Currency",
        suggestedValue: 5.26,
        aiRationale: "Suggested by Strategic Advisor based on competitor's historical low margin of 15%."
      }
    ]
  },
  {
    id: "T7",
    title: "Run Marketing Campaign",
    description: "Set the marketing budget for each product.",
    role: "Sales",
    transactionCode: "ZADS",
    priority: "Medium",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Total_Marketing_Spend", dataType: "Currency", suggestedValue: 50000 }]
  },
  {
    id: "T8",
    title: "Review Financial Statements",
    description: "Analyze the company's financial performance to track profitability.",
    role: "Team Leader",
    transactionCode: "F.01",
    priority: "High",
    estimatedTime: 10,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  // --- NEW PROCUREMENT TASKS ---
  {
    id: "P-R1-1",
    title: "Select Vendor & Check Stock",
    description: "Input: Select Vendor for each RM. CF: Stock Alert if RM Stock < 5,000kg.",
    role: "Procurement",
    transactionCode: "ZMB52 / ZME12",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R1-2",
    title: "Create Purchase Order",
    description: "Create purchase orders for necessary raw materials based on MRP run and stock levels.",
    role: "Procurement",
    transactionCode: "ME59N",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R1-3",
    title: "Sustainability Investment",
    description: "Input: Investment Cost. CF: Target Met if Cumulative CO2 Reduction > 500 kg.",
    role: "Procurement",
    transactionCode: "ZFB50",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
  },
  {
    id: "P-R2+-1",
    title: "Supply, Carbon, & Vendor Check",
    description: "Review supplier performance, carbon impact, and current vendor contracts.",
    role: "Procurement",
    transactionCode: "ZME2N/ZMB52",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-2",
    title: "Select Vendor (Sourcing)",
    description: "Analyze and select vendors for raw materials based on price, quality, and reliability.",
    role: "Procurement",
    transactionCode: "ZME12 (Procurement Sourcing)",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-3",
    title: "Create Purchase Order",
    description: "Automatically or manually create purchase orders based on requisitions from MRP.",
    role: "Procurement",
    transactionCode: "ME59N",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-4",
    title: "Raw Material Stock Check & PO Req.",
    description: "Check stock levels of raw materials and create purchase requisitions if needed.",
    role: "Procurement",
    transactionCode: "ZMB52 (Stock Check)",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-5",
    title: "Contingency: Stock Alert Action",
    description: "Take action on stock alerts, potentially by creating urgent purchase orders.",
    role: "Procurement",
    transactionCode: "ZME12",
    priority: "Medium",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-6",
    title: "Sustainability Investment",
    description: "Post investments related to sustainability initiatives.",
    role: "Procurement",
    transactionCode: "ZFB50 (Financial Postings)",
    priority: "Medium",
    estimatedTime: 3,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
  },
  {
    id: "P-R2+-7",
    title: "Final Lock Confirm: Vendor Save",
    description: "Finalize and save vendor selections for the round.",
    role: "Procurement",
    transactionCode: "ZME12 (Vendor Selection)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-8",
    title: "Final Lock Confirm: Investment Post",
    description: "Finalize and post all financial investments for the round.",
    role: "Procurement",
    transactionCode: "ZFB50 (Investment Posting)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  // --- NEW PRODUCTION TASKS ---
  {
    id: "PM-1-1",
    title: "Validate BOM Change",
    description: "Check/Change Product Design",
    role: "Production",
    transactionCode: "ZCS02",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-2",
    title: "Run MRP",
    description: "Action: Execute MRP. Blocked Alert if P-1-1 is incomplete.",
    role: "Production",
    transactionCode: "MD01",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["P-1-1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-3",
    title: "Set Lot Size & Release Production",
    description: "Input: Production Lot Size. Efficiency Alert if Lot Size < 48,000 units.",
    role: "Production",
    transactionCode: "C041 (Production Release)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["PM-1-2"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Production_Lot_Size", dataType: "Integer" }]
  },
  {
    id: "PM-R2+-1",
    title: "Capacity, Efficiency, & Inventory Check",
    description: "Focus: Finished Goods Stock, Capacity Used, Defect Rate. Check for Overstock if Finished Goods > 100,000 units.",
    role: "Production",
    transactionCode: "ZMB52 (Stock) & ZCOOIS (Production Log)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-R2+-2",
    title: "Validate BOM Change",
    description: "Check/Change Product Design",
    role: "Production",
    transactionCode: "ZCS02",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-R2+-3",
    title: "Run MRP, Set Lot Size, Release",
    description: "Orange if Lot Size < 48,000 units (Inefficiency).",
    role: "Production",
    transactionCode: "MD01/CO41 (MRP/Production Release)",
    priority: "High",
    estimatedTime: 3,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: ["P-X-3"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-R2+-4",
    title: "Execution Lock Confirm",
    description: "Confirm: Production release was successful, and no planned orders remain unconverted. Verify no remaining Planned Orders are pending.",
    role: "Production",
    transactionCode: "C041 (Production Release)",
    priority: "Low",
    estimatedTime: 1,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-R2+-5",
    title: "Capacity & Cost Efficiency",
    description: "If Efficiency Alert is Active: (Lot Size < 48,000): No action is possible this round, but document the cost penalty for the next round's planning. Check with Procurement: Confirm that no raw material shortages are going to stop the currently running batch. If a run is failing, quickly cancel the planned orders (CO41) to free up capacity.",
    role: "Production",
    transactionCode: "CO41",
    priority: "Low",
    estimatedTime: 1,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  }
];
