

import type { UserProfile, GameState, CompetitorLogEntry, PeerData, RoleActionItems, Task } from "@/types";

export const USER_PROFILES: UserProfile[] = [
  { id: 'procurement', name: 'Procurement', avatarUrl: 'https://picsum.photos/seed/procurement/100/100' },
  { id: 'production', name: 'Production', avatarUrl: 'https://picsum.photos/seed/production/100/100' },
  { id: 'logistics', name: 'Logistics', avatarUrl: 'https://picsum.photos/seed/logistics/100/100' },
  { id: 'sales', name: 'Sales', avatarUrl: 'https://picsum.photos/seed/sales/100/100' },
];

export const INITIAL_GAME_STATE: GameState = {
  companyValuation: 50000000,
  netIncome: 2500000,
  inventoryValue: 750000,
  totalEmissions: 1200,
  teamStrategy: "Focus on high-margin products and expand market share in Europe.",
  kpiHistory: [
    { round: 1, companyValuation: 45000000, netIncome: 1800000, inventoryValue: 600000, totalEmissions: 1100 },
  ],
  timerState: {
    timeLeft: 1200,
    isPaused: true,
    isBreakActive: false,
    isBreakEnabled: true,
    roundDuration: 1200, // 20 minutes
    breakDuration: 300, // 5 minutes
  }
};


export const ALL_TASKS: Task[] = [
  // --- ROUND 1 SETUP TASKS ---
  {
    id: "T0.1",
    title: "Confirm Initial Finished Goods Stock",
    description: "Verify and adjust the starting inventory levels for all finished products. This is a one-time setup for Round 1. Use transaction ZMB52 to check current stock.",
    role: "Logistics",
    transactionCode: "ZMB1B (for changes)",
    priority: "Critical",
    estimatedTime: 5,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Nut_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Blueberry_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Strawberry_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Raisin_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Original_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Mixed_Muesli_500g_Initial_Stock", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Nut_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Blueberry_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Strawberry_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Raisin_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Original_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
      { fieldName: "Mixed_Muesli_1kg_Initial_Stock", dataType: "Integer", suggestedValue: 15000 },
    ]
  },
  {
    id: "T0.2",
    title: "Confirm Initial Raw Material Stock",
    description: "Verify and adjust the starting inventory for all raw materials. This is a one-time setup for Round 1. Use transaction ZMB52 to check current stock.",
    role: "Procurement",
    transactionCode: "ZME21N (for changes)",
    priority: "Critical",
    estimatedTime: 5,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Wheat_Initial_Stock_kg", dataType: "Integer", suggestedValue: 20000 },
      { fieldName: "Oats_Initial_Stock_kg", dataType: "Integer", suggestedValue: 30000 },
      { fieldName: "Nuts_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Blueberries_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Strawberries_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Raisins_Initial_Stock_kg", dataType: "Integer", suggestedValue: 5000 },
      { fieldName: "Small_Bag_Initial_Stock_units", dataType: "Integer", suggestedValue: 150000 },
      { fieldName: "Large_Bag_Initial_Stock_units", dataType: "Integer", suggestedValue: 100000 },
      { fieldName: "Small_Box_Initial_Stock_units", dataType: "Integer", suggestedValue: 150000 },
      { fieldName: "Large_Box_Initial_Stock_units", dataType: "Integer", suggestedValue: 100000 },
    ]
  },
  {
    id: "T0.3",
    title: "Validate & Confirm Bill of Materials (BOM)",
    description: "Check the recipes (BOM) for all products to ensure they are correct before starting production. Use ZCS02 to make changes if needed. This is a one-time setup for Round 1.",
    role: "Production",
    transactionCode: "CS03 (View), ZCS02 (Change)",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T0.4",
    title: "Set Initial Prices",
    description: "Set the initial selling price for all products in all distribution channels (DC). This is a critical one-time setup for Round 1.",
    role: "Sales",
    transactionCode: "VK32",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "Once",
    startRound: 1,
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Nut_Muesli_500g_Price", dataType: "Currency", suggestedValue: 3.90 },
      { fieldName: "Blueberry_Muesli_500g_Price", dataType: "Currency", suggestedValue: 4.23 },
      { fieldName: "Nut_Muesli_1kg_Price", dataType: "Currency", suggestedValue: 4.61 },
      { fieldName: "Blueberry_Muesli_1kg_Price", dataType: "Currency", suggestedValue: 5.26 },
    ]
  },
  // --- REGULAR TASKS ---
  {
    id: "T1",
    title: "Forecast Sales",
    description: "Create the sales forecast for all products for the upcoming period.",
    role: "Sales",
    transactionCode: "MD61",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Total_Units_Forecasted", dataType: "Integer", suggestedValue: 370000 },
    ]
  },
  {
    id: "T2",
    title: "Plan Production",
    description: "Run MRP and convert planned orders to production orders.",
    role: "Production",
    transactionCode: "MD01, CO41",
    priority: "Critical",
    estimatedTime: 15,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T3",
    title: "Procure Raw Materials",
    description: "Order raw materials needed for the production plan.",
    role: "Procurement",
    transactionCode: "ZME21N",
    priority: "Critical",
    estimatedTime: 10,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T4",
    title: "Check Inventory Report",
    description: "Continuously monitor inventory levels of raw materials and finished goods.",
    role: "Logistics",
    transactionCode: "ZMB52",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "T5",
    title: "Review Market Reports",
    description: "Analyze market reports to understand competitor pricing and market share.",
    role: "Sales",
    transactionCode: "ZMARKET",
    priority: "High",
    estimatedTime: 10,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "ERPsim Gather Data",
    taskType: "ERPsim Gather Data",
    completed: false,
    dataFields: [{ fieldName: "Competitor_Avg_Price", dataType: "Currency" }]
  },
  {
    id: "T6",
    title: "Set Product Prices",
    description: "Adjust the selling price for all finished products based on strategy and market data.",
    role: "Sales",
    transactionCode: "VK32",
    priority: "High",
    estimatedTime: 8,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: ["T5"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      {
        fieldName: "Blueberry_Muesli_1kg_Price",
        dataType: "Currency",
        suggestedValue: 5.26,
        aiRationale: "Suggested by Strategic Advisor based on competitor's historical low margin of 15%."
      }
    ]
  },
  {
    id: "T7",
    title: "Run Marketing Campaign",
    description: "Set the marketing budget for each product.",
    role: "Sales",
    transactionCode: "ZADS",
    priority: "Medium",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    timeframeConstraint: "StartPhase",
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Total_Marketing_Spend", dataType: "Currency", suggestedValue: 50000 }]
  },
  {
    id: "T8",
    title: "Review Financial Statements",
    description: "Analyze the company's financial performance to track profitability.",
    role: "Team Leader",
    transactionCode: "F.01",
    priority: "High",
    estimatedTime: 10,
    roundRecurrence: "Continuous",
    timeframeConstraint: "None",
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  // --- NEW PROCUREMENT TASKS ---
  {
    id: "P-R1-1",
    title: "Select Vendor & Check Stock",
    description: "Input: Select Vendor for each RM. CF: Stock Alert if RM Stock < 5,000kg.",
    role: "Procurement",
    transactionCode: "ZMB52 / ZME12",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R1-2",
    title: "Create Purchase Order",
    description: "Create purchase orders for necessary raw materials based on MRP run and stock levels.",
    role: "Procurement",
    transactionCode: "ME59N",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R1-3",
    title: "Sustainability Investment",
    description: "Input: Investment Cost. CF: Target Met if Cumulative CO2 Reduction > 500 kg.",
    role: "Procurement",
    transactionCode: "ZFB50",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
  },
  {
    id: "P-R2+-1",
    title: "Supply, Carbon, & Vendor Check",
    description: "Review supplier performance, carbon impact, and current vendor contracts.",
    role: "Procurement",
    transactionCode: "ZME2N/ZMB52",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-2",
    title: "Select Vendor (Sourcing)",
    description: "Analyze and select vendors for raw materials based on price, quality, and reliability.",
    role: "Procurement",
    transactionCode: "ZME12 (Procurement Sourcing)",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-3",
    title: "Create Purchase Order",
    description: "Automatically or manually create purchase orders based on requisitions from MRP.",
    role: "Procurement",
    transactionCode: "ME59N",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-4",
    title: "Raw Material Stock Check & PO Req.",
    description: "Check stock levels of raw materials and create purchase requisitions if needed.",
    role: "Procurement",
    transactionCode: "ZMB52 (Stock Check)",
    priority: "High",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-5",
    title: "Contingency: Stock Alert Action",
    description: "Take action on stock alerts, potentially by creating urgent purchase orders.",
    role: "Procurement",
    transactionCode: "ZME12",
    priority: "Medium",
    estimatedTime: 5,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-6",
    title: "Sustainability Investment",
    description: "Post investments related to sustainability initiatives.",
    role: "Procurement",
    transactionCode: "ZFB50 (Financial Postings)",
    priority: "Medium",
    estimatedTime: 3,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
  },
  {
    id: "P-R2+-7",
    title: "Final Lock Confirm: Vendor Save",
    description: "Finalize and save vendor selections for the round.",
    role: "Procurement",
    transactionCode: "ZME12 (Vendor Selection)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "P-R2+-8",
    title: "Final Lock Confirm: Investment Post",
    description: "Finalize and post all financial investments for the round.",
    role: "Procurement",
    transactionCode: "ZFB50 (Investment Posting)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "RoundStart",
    startRound: 2,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  // --- NEW PRODUCTION TASKS ---
  {
    id: "PM-1-1",
    title: "Validate BOM Change",
    description: "Check/Change Product Design",
    role: "Production",
    transactionCode: "ZCS02",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-2",
    title: "Run MRP",
    description: "Action: Execute MRP. Blocked Alert if P-1-1 is incomplete.",
    role: "Production",
    transactionCode: "MD01",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["P-1-1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-3",
    title: "Set Lot Size & Release Production",
    description: "Input: Production Lot Size. Efficiency Alert if Lot Size < 48,000 units.",
    role: "Production",
    transactionCode: "C041 (Production Release)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["PM-1-1"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Production_Lot_Size", dataType: "Integer" }]
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
      id: `PM-R${round}-1`,
      title: "Capacity, Efficiency, & Inventory Check",
      description: "Focus: Finished Goods Stock, Capacity Used, Defect Rate. Check for Overstock if Finished Goods > 100,000 units. Prepares for Lot Size Decision.",
      role: "Production" as Role,
      transactionCode: "ZMB52 (Stock) & ZCOOIS (Production Log)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false,
    },
    {
      id: `PM-R${round}-2`,
      title: "Validated BOM Change",
      description: "Check/Change Product Design",
      role: "Production" as Role,
      transactionCode: "ZCS02",
      priority: "Medium" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false,
    },
    {
      id: `PM-R${round}-3`,
      title: "Run MRP, Set Lot Size, Release",
      description: "Orange if Lot Size < 48,000 units (Inefficiency).",
      role: "Production" as Role,
      transactionCode: "MD01/CO41 (MRP/Production Release)",
      priority: "High" as TaskPriority,
      estimatedTime: 3,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: ["P-X-3"],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false,
    },
    {
      id: `PM-R${round}-4`,
      title: "Execution Lock Confirm: Production Release",
      description: "Confirm: Production release was successful, and no planned orders remain unconverted. Verify no remaining Planned Orders are pending.",
      role: "Production" as Role,
      transactionCode: "C041 (Production Release)",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false,
    },
    {
      id: `PM-R${round}-5`,
      title: "Capacity & Cost Efficiency",
      description: "If Efficiency Alert is Active (Lot Size < 48,000): No action is possible this round, but document the cost penalty for the next round's planning. Check with Procurement: Confirm that no raw material shortages are going to stop the currently running batch. If a run is failing, quickly cancel the planned orders (CO41) to free up capacity.",
      role: "Production" as Role,
      transactionCode: "CO41",
      priority: "Low" as TaskPriority,
      estimatedTime: 0,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false,
    }
  ]),
    // --- NEW LOGISTICS TASKS ---
  {
    id: "L-1-1",
    title: "Plan Stock Transfer to DCs",
    description: "Input: Qty to Transfer. CF: Stock-Out Risk if DC Stock < 5,000 units.",
    role: "Logistics",
    transactionCode: "ZMB1B",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["PM-1-2"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Quantity_to_Transfer", dataType: "Integer" }]
  },
  {
    id: "L-1-2",
    title: "Monitor Cash Flow & Deliveries",
    description: "CF: Cash Alert if Cash Balance < €100,000. CF: Delivery Alert if PO delivery is late.",
    role: "Logistics",
    transactionCode: "ZFF7B/ZME2N",
    priority: "High",
    estimatedTime: 6,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["L-1-1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
        id: `L-R${round}-1`,
        title: "Cash, Profit, & Liquidity Check",
        description: "Focus: Cash Balance, Total Profit, Accounts Receivable (AR). CF: Red if Cash Balance < €100,000. Prepares for Stock Transfer/Payment Monitoring.",
        role: "Logistics" as Role,
        transactionCode: "ZFF7B/F.01",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-2`,
        title: "Execute Stock Transfer to DCs",
        description: "Transfer finished goods from the main plant to regional distribution centers.",
        role: "Logistics" as Role,
        transactionCode: "ZMB1B (Stock Transfer)",
        priority: "High" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-3`,
        title: "Monitor Delivery & Stock Status",
        description: "Monitor purchase order delivery status and distribution center stock levels.",
        role: "Logistics" as Role,
        transactionCode: "ZME2N (PO Status)",
        priority: "High" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-4`,
        title: "Transfer & Financial Lock Confirm",
        description: "Confirm: Stock Transfer was saved. Final Check: Review ZFF7B to ensure Cash Balance > €0.",
        role: "Logistics" as Role,
        transactionCode: "ZMB1B (Stock Transfer)",
        priority: "Low" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-5`,
        title: "Contingency: PO Hold for Cash",
        description: "If Cash Alert is Active: Immediately alert Procurement to hold or cancel any large pending Purchase Orders (POs) to prevent a bank overdraft.",
        role: "Logistics" as Role,
        transactionCode: "N/A",
        priority: "Medium" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-6`,
        title: "Final Lock Confirm: Transfer Save",
        description: "Confirm: Stock Transfer was saved.",
        role: "Logistics" as Role,
        transactionCode: "ZMB1B (Transfer Lock)",
        priority: "High" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `L-R${round}-7`,
        title: "Final Lock Confirm: Cash Review",
        description: "Review final cash balance (ZFF7B) to ensure no red cash alert is triggered right at the final minute.",
        role: "Logistics" as Role,
        transactionCode: "ZFF7B (Cash Balance)",
        priority: "High" as TaskPriority,
        estimatedTime: 0,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    }
  ]),
    // --- NEW SALES TASKS ---
  {
    id: "S-1-1",
    title: "Round Start Review & Market Analysis",
    description: "Review competitor pricing and market share before forecasting.",
    role: "Sales",
    transactionCode: "ZMARKET",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false,
  },
  {
    id: "S-1-2",
    title: "Set Forecast & Pricing",
    description: "Input: Forecast Units & Prices. CF: Price Alert if price > Comp. Avg. + 10%.",
    role: "Sales",
    transactionCode: "MD61/VK32",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-1"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [
      { fieldName: "Forecast_Units", dataType: "Integer" },
      { fieldName: "Product_Price", dataType: "Currency" },
    ],
  },
  {
    id: "S-1-3",
    title: "Set Marketing Budget",
    description: "Input: Budget Allocation. CF: Low ROI Alert if Projected Marketing ROI < 1.0.",
    role: "Sales",
    transactionCode: "ZADS",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Marketing_Budget", dataType: "Currency" }],
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
        id: `S-R${round}-1`,
        title: "Market, Revenue, & Price Check",
        description: "Focus: Competitor Average Price, Units Sold. CF: Check if Market Share Trend is declining. Prepares for Price Adjustment.",
        role: "Sales" as Role,
        transactionCode: "ZMARKET & Spreadsheet",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `S-R${round}-2`,
        title: "Forecast, Price, & Budget Adjustments",
        description: "CF: Orange if Price > Comp. Avg + 10%. Use Price Elasticity Model.",
        role: "Sales" as Role,
        transactionCode: "MD61/VK32 (Forecast/Pricing)",
        priority: "High" as TaskPriority,
        estimatedTime: 3,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: ["R-X-1"],
        completionType: "Data-Confirmed" as CompletionType,
        taskType: "ERPsim Input Data" as TaskType,
        completed: false,
        dataFields: [
            { fieldName: "Forecast_Units", dataType: "Integer" },
            { fieldName: "Product_Price", dataType: "Currency" },
            { fieldName: "Marketing_Budget", dataType: "Currency" }
        ]
    },
    {
        id: `S-R${round}-3`,
        title: "Final Input Confirmation: ZADS",
        description: "Confirm: ZADS (Marketing Budget) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
        role: "Sales" as Role,
        transactionCode: "ZADS (Marketing Budget)",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `S-R${round}-4`,
        title: "Final Input Confirmation: MD61",
        description: "Confirm: MD61 (Forecast) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
        role: "Sales" as Role,
        transactionCode: "MD61 (Forecast)",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `S-R${round}-5`,
        title: "Final Input Confirmation: VK32",
        description: "Confirm: VK32 (Pricing) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
        role: "Sales" as Role,
        transactionCode: "VK32 (Pricing)",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `S-R${round}-6`,
        title: "Market Reaction & Performance",
        description: "If Price Alert is Active: Analyze market data for the last few days. If sales volume is low, decide if a final price cut is necessary before the round ends to move stock. Check with Production: Are there any finished goods that Production reported as 'overstock' (ZMB52)? If so, consider offering a promotion to clear them.",
        role: "Sales" as Role,
        transactionCode: "ZMB52",
        priority: "Low" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "Continuous" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    }
  ]),
  // --- NEW TEAM LEADER TASKS ---
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
        id: `TL-R${round}-1`,
        title: "Round Start Review & KPI Check",
        description: "Guidance: Review Profit, Cash, Carbon Trends. CF: Red if Cash Balance < €100,000.",
        role: "Team Leader" as Role,
        transactionCode: "F.01/ZVC2",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `TL-R${round}-2`,
        title: "Strategy & Contingency Check",
        description: "Guidance: Use this time to address any Red alerts or unexpected market shifts.",
        role: "Team Leader" as Role,
        transactionCode: "N/A",
        priority: "Medium" as TaskPriority,
        estimatedTime: 3,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: ["L-X-5"],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `TL-R${round}-3`,
        title: "Final Task Sign-Off",
        description: "Guidance: Ensure all data is entered and checkboxes are marked before time runs out.",
        role: "Team Leader" as Role,
        transactionCode: "N/A",
        priority: "High" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: ["R-X-7"],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    },
    {
        id: `TL-R${round}-4`,
        title: "Final Status Verification",
        description: "Action: Team Lead reviews the Round Tasks tab, confirming all high-priority checkpoints are marked Complete. Ensure all sequential checkboxes (S-X-2 through P-X-7) are marked complete. Confirm the Sustainability Investment (ZFB50) was executed if planned.",
        role: "Team Leader" as Role,
        transactionCode: "ZFB50",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false,
    }
  ]),
];



