

import type { UserProfile, GameState, CompetitorLogEntry, PeerData, RoleActionItems, Task, Role, RoundRecurrence, CompletionType, TaskType, TaskPriority } from "@/types";

export const USER_PROFILES: UserProfile[] = [
  { id: 'procurement', name: 'Procurement', avatarUrl: 'https://picsum.photos/seed/procurement/100/100' },
  { id: 'production', name: 'Production', avatarUrl: 'https://picsum.photos/seed/production/100/100' },
  { id: 'logistics', name: 'Logistics', avatarUrl: 'https://picsum.photos/seed/logistics/100/100' },
  { id: 'sales', name: 'Sales', avatarUrl: 'https://picsum.photos/seed/sales/100/100' },
];

export const INITIAL_GAME_STATE: GameState = {
  companyValuation: 50000000,
  netIncome: 2500000,
  inventoryValue: 750000,
  cashBalance: 500000,
  grossMargin: 0.45,
  marketShare: 0.25,
  averageSellingPrice: 350,
  inventoryTurnover: 8.5,
  capacityUtilization: 0.8,
  averagePriceGap: -15, // Negative means we are cheaper
  warehouseCosts: 120000,
  onTimeDeliveryRate: 0.98,
  cumulativeCO2eEmissions: 1200,
  competitorAvgPrice: 15.50,
  grossRevenue: 5500000,
  cogs: 3025000,
  sustainabilityInvestment: 50000,
  teamStrategy: "Focus on high-margin products and expand market share in Europe.",
  kpiHistory: [
    { round: 1, companyValuation: 45000000, netIncome: 1800000, inventoryValue: 600000, cumulativeCO2eEmissions: 1100, cashBalance: 450000, grossMargin: 0.42, marketShare: 0.22, averageSellingPrice: 340, inventoryTurnover: 8.2, capacityUtilization: 0.78, averagePriceGap: -20, warehouseCosts: 110000, onTimeDeliveryRate: 0.97, competitorAvgPrice: 15.60, grossRevenue: 4800000, cogs: 2784000, sustainabilityInvestment: 25000 },
  ],
  timerState: {
    timeLeft: 1200,
    isPaused: true,
    isBreakActive: false,
    isBreakEnabled: true,
    roundDuration: 1200, // 20 minutes
    breakDuration: 300, // 5 minutes
    confirmNextRound: true,
  }
};


export const ALL_TASKS: Task[] = [
  // --- PROCUREMENT TASKS ---
  {
    id: "P-1-1",
    title: "Select Vendor & Check Stock",
    description: "Input: Select Vendor for each RM. CF: Stock Alert if RM Stock < 5,000kg.",
    role: "Procurement",
    transactionCode: "ZMB52",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "P-1-2",
    title: "Select Vendor & Check Stock",
    description: "Input: Select Vendor for each RM. CF: Stock Alert if RM Stock < 5,000kg.",
    role: "Procurement",
    transactionCode: "ZME12",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "P-1-3",
    title: "Create Purchase Order",
    description: "Create purchase orders for necessary raw materials.",
    role: "Procurement",
    transactionCode: "ME59N",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "P-1-4",
    title: "Sustainability Investment",
    description: "Input: Investment Cost. CF: Target Met if Cumulative CO2 Reduction > 500 kg.",
    role: "Procurement",
    transactionCode: "ZFB50",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
      id: `P-${round}-1`,
      title: "Supply, Carbon, & Vendor Check",
      description: "Review supply, carbon impact, and vendor contracts.",
      role: "Procurement" as Role,
      transactionCode: "ZME2N/ZMB52",
      priority: "High" as TaskPriority,
      estimatedTime: 5,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `P-${round}-2`,
      title: "Select Vendor (Sourcing)",
      description: "Analyze and select vendors for raw materials.",
      role: "Procurement" as Role,
      transactionCode: "ZME12 (Procurement Sourcing)",
      priority: "High" as TaskPriority,
      estimatedTime: 5,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
        id: `P-${round}-3`,
        title: "Raw Material Stock Check & PO Req.",
        description: "Check stock levels and create purchase requisitions.",
        role: "Procurement" as Role,
        transactionCode: "ZMB52 (Stock Check)",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
      },
    {
      id: `P-${round}-3A`,
      title: "Create Purchase Order",
      description: "Create purchase orders based on MRP.",
      role: "Procurement" as Role,
      transactionCode: "ME59N",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `P-${round}-4`,
      title: "Contingency: Stock Alert Action",
      description: "Take action on stock alerts, e.g., create urgent POs.",
      role: "Procurement" as Role,
      transactionCode: "ZME12",
      priority: "Medium" as TaskPriority,
      estimatedTime: 5,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `P-${round}-5`,
      title: "Sustainability Investment",
      description: "Post investments for sustainability initiatives.",
      role: "Procurement" as Role,
      transactionCode: "ZFB50 (Financial Postings)",
      priority: "Medium" as TaskPriority,
      estimatedTime: 3,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Data-Confirmed" as CompletionType,
      taskType: "ERPsim Input Data" as TaskType,
      completed: false,
      dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
    },
    {
      id: `P-${round}-6`,
      title: "Final Lock Confirm: Vendor Save",
      description: "Finalize and save vendor selections for the round.",
      role: "Procurement" as Role,
      transactionCode: "ZME12 (Vendor Selection)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `P-${round}-7`,
      title: "Final Lock Confirm: Investment Post",
      description: "Finalize and post all financial investments for the round.",
      role: "Procurement" as Role,
      transactionCode: "ZFB50 (Investment Posting)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
  ]),
    // Round 8 Procurement
    {
        id: "P-8-1",
        title: "Supply, Carbon, & Vendor Check",
        description: "Review supply, carbon impact, and vendor contracts.",
        role: "Procurement",
        transactionCode: "ZME2N/ZMB52",
        priority: "High",
        estimatedTime: 5,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-2",
        title: "Select Vendor (Sourcing)",
        description: "Analyze and select vendors for raw materials.",
        role: "Procurement",
        transactionCode: "ZME12 (Procurement Sourcing)",
        priority: "High",
        estimatedTime: 5,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-3",
        title: "Raw Material Stock Check & PO Req.",
        description: "Check stock levels and create purchase requisitions.",
        role: "Procurement",
        transactionCode: "ZMB52 (Stock Check)",
        priority: "High",
        estimatedTime: 2,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-3A",
        title: "Create Purchase Order",
        description: "Create purchase orders based on MRP.",
        role: "Procurement",
        transactionCode: "ME59N",
        priority: "High",
        estimatedTime: 2,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-4",
        title: "Contingency: Stock Alert Action",
        description: "Take action on stock alerts, e.g., create urgent POs.",
        role: "Procurement",
        transactionCode: "ZME12",
        priority: "Medium",
        estimatedTime: 5,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-5",
        title: "Sustainability Investment",
        description: "Post investments for sustainability initiatives.",
        role: "Procurement",
        transactionCode: "ZFB50 (Financial Postings)",
        priority: "Medium",
        estimatedTime: 3,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Data-Confirmed",
        taskType: "ERPsim Input Data",
        completed: false,
        dataFields: [{ fieldName: "Investment_Cost", dataType: "Currency" }]
    },
    {
        id: "P-8-6",
        title: "Final Lock Confirm: Vendor Save",
        description: "Finalize and save vendor selections for the round.",
        role: "Procurement",
        transactionCode: "ZME12 (Vendor Selection)",
        priority: "High",
        estimatedTime: 2,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },
    {
        id: "P-8-7",
        title: "Final Lock Confirm: Investment Post",
        description: "Finalize and post all financial investments for the round.",
        role: "Procurement",
        transactionCode: "ZFB50 (Investment Posting)",
        priority: "High",
        estimatedTime: 2,
        roundRecurrence: "RoundStart",
        startRound: 8,
        dependencyIDs: [],
        completionType: "Manual-Tick",
        taskType: "Standard",
        completed: false
    },


  // --- PRODUCTION MANAGER TASKS ---
  {
    id: "PM-1-1",
    title: "Validated BOM Change",
    description: "Check/Change Product Design",
    role: "Production",
    transactionCode: "ZCS02",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-2",
    title: "Run MRP",
    description: "Action: Execute MRP. CF: Blocked Alert if P-1-1 is incomplete.",
    role: "Production",
    transactionCode: "MD01",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["P-1-1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "PM-1-3",
    title: "Set Lot Size & Release Production",
    description: "Input: Production Lot Size. CF: Efficiency Alert if Lot Size < 48,000 units.",
    role: "Production",
    transactionCode: "CO41 (Production Release)",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["PM-1-1"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Production_Lot_Size", dataType: "Integer" }]
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
        id: `PM-${round}-1`,
        title: "Validated BOM Change",
        description: "Check/Change Product Design",
        role: "Production" as Role,
        transactionCode: "ZCS02",
        priority: "Medium" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    },
    {
        id: `PM-${round}-2`,
        title: "Capacity, Efficiency, & Inventory Check",
        description: "Focus: Finished Goods Stock, Capacity Used, Defect Rate. CF: Check for Overstock if Finished Goods > 100,000 units. Prepares for Lot Size Decision.",
        role: "Production" as Role,
        transactionCode: "ZMB52 (Stock) & ZCOOIS (Production Log)",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    },
    {
        id: `PM-${round}-4`,
        title: "Run MRP, Set Lot Size, Release",
        description: "CF: Orange if Lot Size < 48,000 units (Inefficiency).",
        role: "Production" as Role,
        transactionCode: "MD01/CO41 (MRP/Production Release)",
        priority: "High" as TaskPriority,
        estimatedTime: 3,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [`P-${round}-3`],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    },
    {
        id: `PM-${round}-5`,
        title: "Execution Lock Confirm: Production Release",
        description: "Confirm: Production release was successful, and no planned orders remain unconverted. Verify no remaining Planned Orders are pending.",
        role: "Production" as Role,
        transactionCode: "CO41 (Production Release)",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    },
    {
        id: `PM-${round}-6`,
        title: "Capacity & Cost Efficiency",
        description: "If Efficiency Alert is Active (Lot Size < 48,000): No action is possible this round, but document the cost penalty for the next round's planning. Check with Procurement: Confirm that no raw material shortages are going to stop the currently running batch. If a run is failing, quickly cancel the planned orders (CO41) to free up capacity.",
        role: "Production" as Role,
        transactionCode: "CO41",
        priority: "Low" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "Continuous" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    }
  ]),

  // --- LOGISTICS TASKS ---
  {
    id: "L-1-1",
    title: "Plan Stock Transfer to DCs",
    description: "Input: Qty to Transfer. CF: Stock-Out Risk if DC Stock < 5,000 units.",
    role: "Logistics",
    transactionCode: "ZMB1B",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["PM-1-2"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Quantity_to_Transfer", dataType: "Integer" }]
  },
  {
    id: "L-1-2",
    title: "Monitor Cash Flow & Deliveries",
    description: "CF: Cash Alert if Cash Balance < €100,000. CF: Delivery Alert if PO delivery is late.",
    role: "Logistics",
    transactionCode: "ZFF7B/ZME2N",
    priority: "High",
    estimatedTime: 6,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["L-1-1"],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
        id: `L-${round}-1`,
        title: "Cash, Profit, & Liquidity Check",
        description: "Focus: Cash Balance, Total Profit, Accounts Receivable (AR). CF: Red if Cash Balance < €100,000. Prepares for Stock Transfer/Payment Monitoring.",
        role: "Logistics" as Role,
        transactionCode: "ZFF7B/F.01",
        priority: "High" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
      },
    {
      id: `L-${round}-2`,
      title: "Execute Stock Transfer to DCs",
      description: "Transfer finished goods from the main plant to regional distribution centers.",
      role: "Logistics" as Role,
      transactionCode: "ZMB1B (Stock Transfer)",
      priority: "High" as TaskPriority,
      estimatedTime: 3,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `L-${round}-3`,
      title: "Monitor Delivery & Stock Status",
      description: "Monitor purchase order delivery status and distribution center stock levels.",
      role: "Logistics" as Role,
      transactionCode: "ZME2N (PO Status)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `L-${round}-3A`,
      title: "Transfer & Financial Lock Confirm",
      description: "Confirm: Stock Transfer was executed and saved to ensure no red cash alert is triggered right at the final minute. Final Check: Review ZFF7B to ensure Cash Balance > €0.",
      role: "Logistics" as Role,
      transactionCode: "ZMB1B (Stock Transfer)",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `L-${round}-4`,
      title: "Contingency: PO Hold for Cash",
      description: "If Cash Alert is Active: Immediately alert Procurement to hold or cancel any large pending Purchase Orders (POs) to prevent a bank overdraft.",
      role: "Logistics" as Role,
      transactionCode: "N/A",
      priority: "Medium" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
        id: `L-${round}-4A`,
        title: "Transfer & Financial Lock Confirm",
        description: "Review final cash balance (ZFF7B) to ensure no red cash alert is triggered right at the final minute.",
        role: "Logistics" as Role,
        transactionCode: "ZFF7B (cash balance)",
        priority: "Low" as TaskPriority,
        estimatedTime: 1,
        roundRecurrence: "RoundStart" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
    },
    {
      id: `L-${round}-5`,
      title: "Final Lock Confirm: Transfer Save",
      description: "Finalize and save the stock transfer.",
      role: "Logistics" as Role,
      transactionCode: "ZMB1B (Transfer Lock)",
      priority: "High" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
        id: `L-${round}-5A`,
        title: "Financial Stability (Liquidity)",
        description: "If Cash Alert is Active: Immediately alert Procurement to hold or cancel any large pending Purchase Orders (POs) to prevent a bank overdraft. Check with Sales: Are transfers still on track to meet the latest forecast? If cash is tight, prioritize stock transfer to high-volume/fast-paying DCs (Grocery Chains).",
        role: "Logistics" as Role,
        transactionCode: "N/A",
        priority: "Low" as TaskPriority,
        estimatedTime: 2,
        roundRecurrence: "Continuous" as RoundRecurrence,
        startRound: round,
        dependencyIDs: [],
        completionType: "Manual-Tick" as CompletionType,
        taskType: "Standard" as TaskType,
        completed: false
      },
    {
      id: `L-${round}-6`,
      title: "Final Lock Confirm: Cash Review",
      description: "Review final cash balance (ZFF7B) to ensure no red cash alert is triggered right at the final minute. Check with Sales if transfers are on track and prioritize stock transfer to high-volume/fast-paying DCs.",
      role: "Logistics" as Role,
      transactionCode: "ZFF7B (Cash Balance)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
  ]),

  // --- SALES TASKS ---
  {
    id: "S-1-1",
    title: "Round Start Review & Market Analysis",
    description: "Review competitor pricing and market share before forecasting.",
    role: "Sales",
    transactionCode: "ZMARKET",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: [],
    completionType: "Manual-Tick",
    taskType: "Standard",
    completed: false
  },
  {
    id: "S-1-2",
    title: "Set Forecast & Pricing",
    description: "Input: Forecast Units & Prices. CF: Price Alert if price > Comp. Avg. + 10%.",
    role: "Sales",
    transactionCode: "MD61/VK32",
    priority: "High",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-1"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Forecast_Units", dataType: "Integer" }, { fieldName: "Product_Price", dataType: "Currency" }]
  },
  {
    id: "S-1-3",
    title: "Set Marketing Budget",
    description: "Input: Budget Allocation. CF: Low ROI Alert if Projected Marketing ROI < 1.0.",
    role: "Sales",
    transactionCode: "ZADS",
    priority: "Medium",
    estimatedTime: 2,
    roundRecurrence: "Once",
    startRound: 1,
    dependencyIDs: ["S-1-2"],
    completionType: "Data-Confirmed",
    taskType: "ERPsim Input Data",
    completed: false,
    dataFields: [{ fieldName: "Marketing_Budget", dataType: "Currency" }]
  },
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
      id: `S-${round}-1`,
      title: "Market, Revenue, & Price Check",
      description: "Focus: Competitor Average Price, Units Sold. CF: Check if Market Share Trend is declining. Prepares for Price Adjustment.",
      role: "Sales" as Role,
      transactionCode: "ZMARKET & Spreadsheet",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `S-${round}-2`,
      title: "Forecast, Price, & Budget Adjustments",
      description: "CF: Orange if Price > Comp. Avg + 10%. Use Price Elasticity Model.",
      role: "Sales" as Role,
      transactionCode: "MD61/VK32 (Forecast/Pricing)",
      priority: "High" as TaskPriority,
      estimatedTime: 3,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [`L-${round}-1`],
      completionType: "Data-Confirmed" as CompletionType,
      taskType: "ERPsim Input Data" as TaskType,
      completed: false,
      dataFields: [{ fieldName: "Forecast_Units", dataType: "Integer" }, { fieldName: "Product_Price", dataType: "Currency" }, { fieldName: "Marketing_Budget", dataType: "Currency" }]
    },
    {
      id: `S-${round}-3`,
      title: "Final Input Confirmation: ZADS",
      description: "Confirm: ZADS (Marketing Budget) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
      role: "Sales" as Role,
      transactionCode: "ZADS (Marketing Budget)",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `S-${round}-4`,
      title: "Final Input Confirmation: MD61",
      description: "Confirm: MD61 (Forecast) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
      role: "Sales" as Role,
      transactionCode: "MD61 (Forecast)",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `S-${round}-5`,
      title: "Final Input Confirmation: VK32",
      description: "Confirm: VK32 (Pricing) were saved in SAP and that the data on the spreadsheet matches the ERP system.",
      role: "Sales" as Role,
      transactionCode: "VK32 (Pricing)",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `S-${round}-6`,
      title: "Market Reaction & Performance",
      description: "If Price Alert is Active: Analyze market data for the last few days. If sales volume is low, decide if a final price cut is necessary before the round ends to move stock. Check with Production: Are there any finished goods that Production reported as 'overstock' (ZMB52)? If so, consider offering a promotion to clear them.",
      role: "Sales" as Role,
      transactionCode: "ZMB52",
      priority: "Low" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "Continuous" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
  ]),

  // --- TEAM LEADER TASKS ---
  ...Array.from({ length: 7 }, (_, i) => i + 2).flatMap(round => [
    {
      id: `T-${round}-1`,
      title: "Round Start Review & KPI Check",
      description: "Guidance: Review Profit, Cash, Carbon Trends. CF: Red if Cash Balance < €100,000.",
      role: "Team Leader" as Role,
      transactionCode: "F.01/ZVC2 (Financial/Sales Reports)",
      priority: "High" as TaskPriority,
      estimatedTime: 2,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `T-${round}-2`,
      title: "Strategy & Contingency Check",
      description: "Guidance: Use this time to address any Red alerts or unexpected market shifts.",
      role: "Team Leader" as Role,
      transactionCode: "N/A",
      priority: "Medium" as TaskPriority,
      estimatedTime: 3,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [`L-${round}-5`],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `T-${round}-3`,
      title: "Final Task Sign-Off",
      description: "Guidance: Ensure all data is entered and checkboxes are marked before time runs out.",
      role: "Team Leader" as Role,
      transactionCode: "N/A",
      priority: "High" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [`P-${round}-7`],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    },
    {
      id: `T-${round}-4`,
      title: "Final Status Verification",
      description: "Action: Team Lead reviews the Round Tasks tab, confirming all high-priority checkpoints are marked Complete. Ensure all sequential checkboxes are marked complete. Confirm the Sustainability Investment (ZFB50) was executed if planned.",
      role: "Team Leader" as Role,
      transactionCode: "ZFB50",
      priority: "Low" as TaskPriority,
      estimatedTime: 1,
      roundRecurrence: "RoundStart" as RoundRecurrence,
      startRound: round,
      dependencyIDs: [],
      completionType: "Manual-Tick" as CompletionType,
      taskType: "Standard" as TaskType,
      completed: false
    }
  ])
];
